site:
  title: Training Courses
  start_page: ROOT::index.adoc
  keys:
    language: en
content:
  sources:
    - url: .
      start_path: ./en/home
      branches: HEAD
    - url: https://docs.gbif.org/course-introduction-to-gbif
      start_path: ./en/intro-to-gbif
      branches: HEAD
    - url: https://docs.gbif.org/course-data-mobilization
      start_path: ./en/data-mobilization
      branches: HEAD
    - url: .
      start_path: ./en/data-use
      branches: HEAD    
    - url: https://docs.gbif.org/course-dna-barcoding
      start_path: ./en/dna-barcoding
      branches: HEAD      
    - url: .
      start_path: ./en/nodes
      branches: HEAD         
    - url: https://docs.gbif.org/course-establishing-gbif-nodes
      start_path: ./en/epn
      branches: HEAD         
output:
  clean: false
  dir: ./output/en
runtime:
  fetch: false
  cache_dir: ./cache
ui:
  bundle:
    url: https://builds.gbif.org/job/tech-docs-theme/lastSuccessfulBuild/artifact/build/ui-bundle.zip
    #url: ui-bundle.zip
    snapshot: true
  supplemental_files: ./supplemental_ui
asciidoc:
  attributes:
    idprefix: ''
    idseparator: '-'
    page-pagination: yes
    page-toctitle: 'Page contents'
    language: en
    null: ␀
antora:
  extensions:
  - require: '@antora/lunr-extension'
    index_latest_only: true
    languages: [en]
